version: '3'
services:
  postges_movie_db:
    container_name: postges_movie_db
    image: postgres:13.4
    restart: unless-stopped
    expose: 
      - '5432'
    volumes: 
      - ../postgres:/var/lib/postgresql/data
    env_file:
      - ./movies_admin/.env
    ports:
      - "5432:5432"

  movies_admin:
    container_name: movies_admin
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file: 
      - ./movies_admin/.env
    volumes: 
      - ./movies_admin/static:/code/static
    depends_on: 
      - postges_movie_db

  # nginx:
  #   image: nginx:1.21.1
  #   container_name: nginx
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #     - ./movies_admin/static:/code/static
  #   depends_on:
  #     - movies_admin
  #   ports:
  #     - "80:80"