version: '3'
services:
  postges_movie_db:
    container_name: postges_movie_db
    image: postgres:13.4
    restart: unless-stopped
    expose: 
      - '5432'
    volumes: 
      - ../postgres:/var/lib/postgresql/data
    env_file:
      - ./movies_admin/.env
    ports:
      - "5432:5432"

  movies_admin:
    container_name: movies_admin
    build:
      context: .
      dockerfile: Dockerfile_django
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    expose:
      - "8000"
    env_file: 
      - ./movies_admin/.env
    volumes:
      - static_volume:/code/staticfiles
    depends_on: 
      - postges_movie_db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile_nginx
    volumes:
      - static_volume:/code/staticfiles
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - movies_admin
volumes:
  static_volume: